config/routes.rb
Rails.application.routes.draw do
  root 'things#index'
  resources :things

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    @things = Thing.all
  end

  def new
    @thing = Thing.new
  end

  def create
    @thing = Thing.new(thing_params)
    if @thing.save
      redirect_to things_path
      flash[:notice] = "Item successfully added to your list!"
    else
      render :new
    end
  end

  def show
    @thing=Thing.find(params[:id])
  end

  def edit
    @thing =Thing.find(params[:id])
  end

  def update
    @thing=Thing.find(params[:id])
    if @thing.update(thing_params)
      redirect_to thing_path
    else
      render :edit
    end
  end

  def destroy
    thing=Thing.find(params[:id])
    thing.destroy
    redirect_to things_path
  end

private
  def thing_params
    params.require(:thing).permit(:item, :priority, :description, :estimated_cost)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RyansShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/things/edit.html.erb
<%=form_for @thing do |thing|%>
<%=thing.label :item%>
<%=thing.text_field :item%>
<br>
<%=thing.label :priority%>
<%=thing.text_field :priority%>
<br>
<%=thing.label :description %>
<%=thing.text_area :description%>
<br>
<%=thing.label :estimated_cost %>
<%=thing.number_field :estimated_cost%>
<br>
<%=thing.submit "Update item"%>
<%end%>

app/views/things/index.html.erb
<%@things.each do |thing|%>
  <%=link_to thing.item, thing%>
  <br>

  <br>
<%end%>
<br>
<%=link_to "Add Item", new_thing_path%>

app/views/things/new.html.erb
<%=form_for @thing do |thing|%>
<%=thing.label :item%>
<%=thing.text_field :item%>
<br>
<%=thing.label :priority%>
<%=thing.text_field :priority%>
<br>
<%=thing.label :description %>
<%=thing.text_area :description%>
<br>
<%=thing.label :estimated_cost %>
<%=thing.number_field :estimated_cost%>
<br>
<%=thing.submit "Add item to list"%>
<%end%>

app/views/things/show.html.erb
<%=@thing.item%>
<%=@thing.priority%>
<%=@thing.description%>
<%=@thing.estimated_cost%>
<%=link_to "Edit Item", edit_thing_path%>
<%=link_to "Delete Item", @thing, method: :delete%>
<%=link_to "Home", things_path%>